## Student ID : 111522071

In [337]:
# import library you use
import numpy as np
import pandas as pd

# Training phase

### Load Data

In [338]:
# load train.csv and training-label.csv
raw_train_x = pd.read_csv("train.csv")
raw_train_y = pd.read_csv("train_label.csv")
# print(raw_train_x)
# print(raw_train_y)

### Data Preprocessing

In [339]:
# drop created_time column
raw_train_x.drop('created_time',axis=1,inplace=True)
print(raw_train_x.info())
print(raw_train_y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33227 entries, 0 to 33226
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mac_hash     33227 non-null  object
 1   sniffer_loc  33227 non-null  int64
dtypes: int64(1), object(1)
memory usage: 519.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5568 entries, 0 to 5567
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mac_hash  5568 non-null   object
 1   label     5568 non-null   int64
dtypes: int64(1), object(1)
memory usage: 87.1+ KB
None

In [340]:
train_x = raw_train_x.drop(['sniffer_loc'], axis=1)
train_x = train_x.groupby(['mac_hash']).sum()

for i in range(1,15):
    train_x[i] = 0

print(train_x.info())

# for i in range(33227):
#     print(str(raw_train_x.loc[i]['mac_hash']))
#     print(raw_train_x.loc[i,'sniffer_loc'])
#     if i == 20:
#         break

<class 'pandas.core.frame.DataFrame'>
Index: 5568 entries, 0003ae8541d0e925fcee242287e2ad27 to fff2ca0333532d6348d5b4fa39028dd4
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       5568 non-null   int64
 1   2       5568 non-null   int64
 2   3       5568 non-null   int64
 3   4       5568 non-null   int64
 4   5       5568 non-null   int64
 5   6       5568 non-null   int64
 6   7       5568 non-null   int64
 7   8       5568 non-null   int64
 8   9       5568 non-null   int64
 9   10      5568 non-null   int64
 10  11      5568 non-null   int64
 11  12      5568 non-null   int64
 12  13      5568 non-null   int64
 13  14      5568 non-null   int64
dtypes: int64(14)
memory usage: 652.5+ KB
None
10f6ad2e3fa3b3da8ceb3fbd95658681
2
10f6ad2e3fa3b3da8ceb3fbd95658681
10
10f6ad2e3fa3b3da8ceb3fbd95658681
9
10f6ad2e3fa3b3da8ceb3fbd95658681
6
10f6ad2e3fa3b3da8ceb3fbd95658681
4
10f6ad2e3fa3b3da8ceb3fbd95658681
5
10f6ad2e3fa3b3da8ceb3fbd95658681
3
10f6ad2e3fa3b3da8ceb3fbd95658681
7
10f6ad2e3fa3b3da8ceb3fbd95658681
12
10f6ad2e3fa3b3da8ceb3fbd95658681
11
10f6ad2e3fa3b3da8ceb3fbd95658681
14
5272841b630d74290ec129c64dd6378b
12
8ab74d094708a27c9660e897b93a50f9
6
8ab74d094708a27c9660e897b93a50f9
8
8ab74d094708a27c9660e897b93a50f9
9
8ab74d094708a27c9660e897b93a50f9
7
8ab74d094708a27c9660e897b93a50f9
2
8ab74d094708a27c9660e897b93a50f9
11
8ab74d094708a27c9660e897b93a50f9
10
8ab74d094708a27c9660e897b93a50f9
4
8ab74d094708a27c9660e897b93a50f9
3

In [341]:
# Count whether each mac_hash has passed through these 14 locations, and generate a training dataframe


for i in range(33227):
    train_x.loc[raw_train_x.loc[i]['mac_hash'],raw_train_x.loc[i,'sniffer_loc']]=1
    
print(train_x.head(15))

                                  1   2   3   4   5   6   7   8   9   10  11  \
mac_hash
0003ae8541d0e925fcee242287e2ad27   0   0   0   0   0   0   0   0   0   0   1
00078611037990f7f36b722f22595fe7   0   1   1   1   1   1   0   1   0   1   1
000ce31739b333d931813de403156844   1   1   1   1   1   1   1   1   1   1   1
0027240b2aeb1f7f3c053c073cafb452   0   1   0   1   1   1   1   1   1   1   1
0028a89964416dc9a8a66cc7fe25ef4e   0   1   1   1   0   1   0   0   1   1   1
002ccce0dc6384e91e6aaa988b542c45   0   0   1   0   0   0   0   0   0   0   0
00414318025c30f1360225ad736aa298   0   1   1   1   1   1   1   0   1   1   1
0041999224addbf0753762647ac2166b   0   1   1   1   1   1   0   1   1   1   1
0044e62541626e25e041b4baf3daea4c   0   1   1   1   1   1   0   1   1   1   0
0052939102fb0acda914e30b560a5900   0   1   1   1   0   0   0   0   0   1   1
00605a68f5fe01ee37e7fb6169fdbc5c   0   0   0   0   0   0   0   0   1   1   1
007776e9906aba0186587d85895a472a   1   0   0   0   0   0   0   0   0   0   0
00782214b7ce1c28fd9d2a9347c0520f   0   1   0   0   0   0   0   0   0   0   0
00849ab004fe31d8d3a4b3f4bb794d7b   0   0   0   0   0   0   0   0   0   0   0
009ed7f547cd586aa527b4279ab83865   0   1   1   1   0   1   1   1   1   1   1

                                  12  13  14
mac_hash
0003ae8541d0e925fcee242287e2ad27   0   0   0
00078611037990f7f36b722f22595fe7   0   0   0
000ce31739b333d931813de403156844   1   1   1
0027240b2aeb1f7f3c053c073cafb452   1   1   1
0028a89964416dc9a8a66cc7fe25ef4e   1   1   1
002ccce0dc6384e91e6aaa988b542c45   0   0   0
00414318025c30f1360225ad736aa298   1   1   0
0041999224addbf0753762647ac2166b   1   1   0
0044e62541626e25e041b4baf3daea4c   1   1   1
0052939102fb0acda914e30b560a5900   0   1   0
00605a68f5fe01ee37e7fb6169fdbc5c   1   1   0
007776e9906aba0186587d85895a472a   0   0   0
00782214b7ce1c28fd9d2a9347c0520f   0   0   0
00849ab004fe31d8d3a4b3f4bb794d7b   0   0   1
009ed7f547cd586aa527b4279ab83865   1   1   0

In [342]:
# Add label column
train_x = pd.merge(train_x,raw_train_y,on='mac_hash')
train_x

,mac_hash,1,2,3,4,5,6,7,8,9,10,11,12,13,14,label
0,0003ae8541d0e925fcee242287e2ad27,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,00078611037990f7f36b722f22595fe7,0,1,1,1,1,1,0,1,0,1,1,0,0,0,1
2,000ce31739b333d931813de403156844,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3
3,0027240b2aeb1f7f3c053c073cafb452,0,1,0,1,1,1,1,1,1,1,1,1,1,1,4
4,0028a89964416dc9a8a66cc7fe25ef4e,0,1,1,1,0,1,0,0,1,1,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,ffbf58ded2902366bcae7aa5e468556c,0,1,1,1,1,1,0,1,1,1,1,1,0,1,4
5564,ffc343f03f0c9dbd06439ddff42922c0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
5565,ffca215be2cb1505d931bd162da60104,0,1,1,1,1,1,0,1,0,1,0,1,1,0,4
5566,ffd7be58ee3c3fb47530ae7e4f251f88,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
5567,fff2ca0333532d6348d5b4fa39028dd4,0,0,1,0,0,0,0,0,1,1,1,1,1,0,2

### Training

In [343]:
# X: feature from training dataframe
X = train_x.iloc[:,:-1]
X

,mac_hash,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0003ae8541d0e925fcee242287e2ad27,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,00078611037990f7f36b722f22595fe7,0,1,1,1,1,1,0,1,0,1,1,0,0,0
2,000ce31739b333d931813de403156844,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,0027240b2aeb1f7f3c053c073cafb452,0,1,0,1,1,1,1,1,1,1,1,1,1,1
4,0028a89964416dc9a8a66cc7fe25ef4e,0,1,1,1,0,1,0,0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,ffbf58ded2902366bcae7aa5e468556c,0,1,1,1,1,1,0,1,1,1,1,1,0,1
5564,ffc343f03f0c9dbd06439ddff42922c0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
5565,ffca215be2cb1505d931bd162da60104,0,1,1,1,1,1,0,1,0,1,0,1,1,0
5566,ffd7be58ee3c3fb47530ae7e4f251f88,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5567,fff2ca0333532d6348d5b4fa39028dd4,0,0,1,0,0,0,0,0,1,1,1,1,1,0

In [344]:
# Y: label from training dataframe
# you need to change your label from categorical encoding to one-hot encoding
Y = train_x.iloc[:,-1:]
Y

      label
0         0
1         1
2         3
3         4
4         4
...     ...
5563      4
5564      0
5565      4
5566      0
5567      2

[5568 rows x 1 columns]

In [345]:
# split your dataset as training dataset and validation dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)
print(X_train)

                              mac_hash  1  2  3  4  5  6  7  8  9  10  11  12  \
253   0bb7bc32760c4684ec99bc017bd5d5a9  0  1  1  1  1  1  1  1  1   1   1   1
1114  33979e1dfb86170bea9c7d344796c775  0  1  0  1  1  1  1  1  1   1   1   1
4257  c419c760ea2240a58f887576a649e758  0  1  1  1  1  1  0  0  1   1   1   1
3979  b71b3b92ebf7c11c057c7891339d5a8f  1  1  1  0  0  1  0  0  0   0   0   0
1012  2ebd525772779163cebae4fe5e022a55  0  1  0  0  1  0  0  0  0   0   0   1
...                                ... .. .. .. .. .. .. .. .. ..  ..  ..  ..
4931  e3f2c53a21b80b5cfcc579ddb387aade  0  0  0  0  0  0  0  0  0   0   0   1
3264  97a50c5f8abb7469251e87df8f805a0d  0  1  1  1  1  1  1  1  1   0   1   1
1653  4c032d3c5ca284fd54942383682d0f58  1  1  1  1  0  1  1  1  1   1   1   1
2607  798c9871bee36493c6972ed86dfaea4e  0  0  0  1  0  1  0  0  0   0   0   0
2732  7f3a6f6ef0b41298f938fe5dd26c5025  0  1  1  1  1  1  0  1  1   1   1   1

      13  14
253    1   0
1114   1   1
4257   1   0
3979   0   0
1012   0   0
...   ..  ..
4931   0   1
3264   1   0
1653   1   1
2607   0   0
2732   1   1

[4454 rows x 15 columns]

In [346]:
print(X_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4454 entries, 253 to 2732
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mac_hash  4454 non-null   object
 1   1         4454 non-null   int64
 2   2         4454 non-null   int64
 3   3         4454 non-null   int64
 4   4         4454 non-null   int64
 5   5         4454 non-null   int64
 6   6         4454 non-null   int64
 7   7         4454 non-null   int64
 8   8         4454 non-null   int64
 9   9         4454 non-null   int64
 10  10        4454 non-null   int64
 11  11        4454 non-null   int64
 12  12        4454 non-null   int64
 13  13        4454 non-null   int64
 14  14        4454 non-null   int64
dtypes: int64(14), object(1)
memory usage: 556.8+ KB
None

In [347]:
from sklearn import preprocessing
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaledFeatures=minmax_scale.fit_transform(X_train)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [ ]:
# build DNN model
import keras.models as k_models
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam
from tensorflow import keras

model = k_models.Sequential()
model.add(Dense(input_dim = 15,units=40,activation='relu'))
model.add(Dense(units=100,activation='relu'))
model.add(Dense(units=5,activation='sigmoid'))

In [ ]:
# start train model
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['acc'])
model.fit(x=X_train,y=Y_train,batch_size=100,epochs=20)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).

In [ ]:
# validate your model using validation dataset
# After prediction, you need to change your result and label from one-hot encoding to categorical encoding

In [ ]:
# using sklearn classification_report function to show your validation result

# Testing phase

### Load Data

In [ ]:
# load test.csv file as dataframe

### Data Preprocessing

In [ ]:
# Preprocessing is the same as training

### Predict the result using your model

In [ ]:
# X_test: feature

In [ ]:
# Prediction

In [ ]:
# Generate submit.csv