## Student ID : 111522071

In [1]:
# import library you use
import numpy as np
import pandas as pd

# Training phase

### Load Data

In [2]:
# load train.csv and training-label.csv
raw_train_x = pd.read_csv("train.csv")
raw_train_y = pd.read_csv("train_label.csv")
# print(raw_train_x)
# print(raw_train_y)

### Data Preprocessing

In [3]:
# drop created_time column
raw_train_x.drop('created_time',axis=1,inplace=True)
print(raw_train_x.info())
print(raw_train_y.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33227 entries, 0 to 33226
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mac_hash     33227 non-null  object
 1   sniffer_loc  33227 non-null  int64
dtypes: int64(1), object(1)
memory usage: 519.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5568 entries, 0 to 5567
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mac_hash  5568 non-null   object
 1   label     5568 non-null   int64
dtypes: int64(1), object(1)
memory usage: 87.1+ KB
None

In [4]:
# print(raw_train_x)

train_x = raw_train_x.drop(['sniffer_loc'], axis=1)

for i in range(1,15):
    train_x[str(i)] = 0

print(train_x)

                               mac_hash  1  2  3  4  5  6  7  8  9  10  11  \
0      10f6ad2e3fa3b3da8ceb3fbd95658681  0  0  0  0  0  0  0  0  0   0   0
1      10f6ad2e3fa3b3da8ceb3fbd95658681  0  0  0  0  0  0  0  0  0   0   0
2      10f6ad2e3fa3b3da8ceb3fbd95658681  0  0  0  0  0  0  0  0  0   0   0
3      10f6ad2e3fa3b3da8ceb3fbd95658681  0  0  0  0  0  0  0  0  0   0   0
4      10f6ad2e3fa3b3da8ceb3fbd95658681  0  0  0  0  0  0  0  0  0   0   0
...                                 ... .. .. .. .. .. .. .. .. ..  ..  ..
33222  13a3e10f950d8050ab5437cf30a3c2c6  0  0  0  0  0  0  0  0  0   0   0
33223  13a3e10f950d8050ab5437cf30a3c2c6  0  0  0  0  0  0  0  0  0   0   0
33224  13a3e10f950d8050ab5437cf30a3c2c6  0  0  0  0  0  0  0  0  0   0   0
33225  13a3e10f950d8050ab5437cf30a3c2c6  0  0  0  0  0  0  0  0  0   0   0
33226  13a3e10f950d8050ab5437cf30a3c2c6  0  0  0  0  0  0  0  0  0   0   0

       12  13  14
0       0   0   0
1       0   0   0
2       0   0   0
3       0   0   0
4       0   0   0
...    ..  ..  ..
33222   0   0   0
33223   0   0   0
33224   0   0   0
33225   0   0   0
33226   0   0   0

[33227 rows x 15 columns]

In [5]:
# Count whether each mac_hash has passed through these 14 locations, and generate a training dataframe
for i in range(raw_train_x.shape[0]):
    s = str(raw_train_x.loc[i,'sniffer_loc'])
    train_x.loc[i,s]=1

train_x = train_x.groupby(['mac_hash'], as_index=False).sum()

print(train_x.head(15))

                            mac_hash  1  2  3  4  5  6  7  8  9  10  11  12  \
0   0003ae8541d0e925fcee242287e2ad27  0  0  0  0  0  0  0  0  0   0   1   0
1   00078611037990f7f36b722f22595fe7  0  1  1  1  1  1  0  1  0   1   1   0
2   000ce31739b333d931813de403156844  1  1  1  1  1  1  1  1  1   1   1   1
3   0027240b2aeb1f7f3c053c073cafb452  0  1  0  1  1  1  1  1  1   1   1   1
4   0028a89964416dc9a8a66cc7fe25ef4e  0  1  1  1  0  1  0  0  1   1   1   1
5   002ccce0dc6384e91e6aaa988b542c45  0  0  1  0  0  0  0  0  0   0   0   0
6   00414318025c30f1360225ad736aa298  0  1  1  1  1  1  1  0  1   1   1   1
7   0041999224addbf0753762647ac2166b  0  1  1  1  1  1  0  1  1   1   1   1
8   0044e62541626e25e041b4baf3daea4c  0  1  1  1  1  1  0  1  1   1   0   1
9   0052939102fb0acda914e30b560a5900  0  1  1  1  0  0  0  0  0   1   1   0
10  00605a68f5fe01ee37e7fb6169fdbc5c  0  0  0  0  0  0  0  0  1   1   1   1
11  007776e9906aba0186587d85895a472a  1  0  0  0  0  0  0  0  0   0   0   0
12  00782214b7ce1c28fd9d2a9347c0520f  0  1  0  0  0  0  0  0  0   0   0   0
13  00849ab004fe31d8d3a4b3f4bb794d7b  0  0  0  0  0  0  0  0  0   0   0   0
14  009ed7f547cd586aa527b4279ab83865  0  1  1  1  0  1  1  1  1   1   1   1

    13  14
0    0   0
1    0   0
2    1   1
3    1   1
4    1   1
5    0   0
6    1   0
7    1   0
8    1   1
9    1   0
10   1   0
11   0   0
12   0   0
13   0   1
14   1   0

In [6]:
train_y = raw_train_y.drop(['label'], axis=1)

for i in range(0,5):
    train_y["t{}".format(str(i))] = 0

print(train_y)

for i in range(5568):
    l = str(int(raw_train_y.loc[i,'label']))
    s = "t{}".format(l)
    train_y.loc[i,s]=1


print(train_y.head(15))

                              mac_hash  t0  t1  t2  t3  t4
0     10f6ad2e3fa3b3da8ceb3fbd95658681   0   0   0   0   0
1     5272841b630d74290ec129c64dd6378b   0   0   0   0   0
2     8ab74d094708a27c9660e897b93a50f9   0   0   0   0   0
3     3d00887dd6e574dd63974bc6c69b23b0   0   0   0   0   0
4     6461fce7f6f184401c961fda75069262   0   0   0   0   0
...                                ...  ..  ..  ..  ..  ..
5563  82498aa0a931e2f37fd29998a77c6dd0   0   0   0   0   0
5564  656ddc677dcb8661ff5d782742fcecfd   0   0   0   0   0
5565  98d389a4b2f378f8217a02416aaa9349   0   0   0   0   0
5566  1eff5eae7401ee128798660ea6b6f09b   0   0   0   0   0
5567  13a3e10f950d8050ab5437cf30a3c2c6   0   0   0   0   0

[5568 rows x 6 columns]
                            mac_hash  t0  t1  t2  t3  t4
0   10f6ad2e3fa3b3da8ceb3fbd95658681   0   0   0   0   1
1   5272841b630d74290ec129c64dd6378b   1   0   0   0   0
2   8ab74d094708a27c9660e897b93a50f9   0   0   0   1   0
3   3d00887dd6e574dd63974bc6c69b23b0   0   1   0   0   0
4   6461fce7f6f184401c961fda75069262   0   1   0   0   0
5   59d12b70529fddfe65db1d5e2a876944   0   0   0   1   0
6   6706689db463be6ce7d4c9aa6e18fb8a   0   0   0   1   0
7   607ee81deecc0d451c50b6f229d5e428   0   1   0   0   0
8   691fdbfa0e2970d0c11e112a971258f6   0   1   0   0   0
9   d36cd7fa91dd21d7592b5ccc450ca911   0   0   0   0   1
10  61d3472cead1c8e3729bd1a0438fd4e9   0   1   0   0   0
11  0992b03f0ca228aae26bbaf3d6a72b20   0   0   0   0   1
12  9d3a8c7b5784f46fcca897bca9267ad5   1   0   0   0   0
13  0942eefaef64a290e4ed65b07edde833   0   0   0   0   1
14  91300f9931c13c5e9c0c57ed3d3b60a2   0   1   0   0   0

In [7]:
# Add label column
train_x = pd.merge(train_x,train_y,on='mac_hash')
train_x

,mac_hash,1,2,3,4,5,6,7,8,9,10,11,12,13,14,t0,t1,t2,t3,t4
0,0003ae8541d0e925fcee242287e2ad27,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,00078611037990f7f36b722f22595fe7,0,1,1,1,1,1,0,1,0,1,1,0,0,0,0,1,0,0,0
2,000ce31739b333d931813de403156844,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0
3,0027240b2aeb1f7f3c053c073cafb452,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1
4,0028a89964416dc9a8a66cc7fe25ef4e,0,1,1,1,0,1,0,0,1,1,1,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,ffbf58ded2902366bcae7aa5e468556c,0,1,1,1,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1
5564,ffc343f03f0c9dbd06439ddff42922c0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5565,ffca215be2cb1505d931bd162da60104,0,1,1,1,1,1,0,1,0,1,0,1,1,0,0,0,0,0,1
5566,ffd7be58ee3c3fb47530ae7e4f251f88,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5567,fff2ca0333532d6348d5b4fa39028dd4,0,0,1,0,0,0,0,0,1,1,1,1,1,0,0,0,1,0,0

### Training

In [26]:
# X: feature from training dataframe
X = train_x.iloc[:,:-5].drop('mac_hash',axis=1)
X

,mac_hash,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0003ae8541d0e925fcee242287e2ad27,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,00078611037990f7f36b722f22595fe7,0,1,1,1,1,1,0,1,0,1,1,0,0,0
2,000ce31739b333d931813de403156844,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,0027240b2aeb1f7f3c053c073cafb452,0,1,0,1,1,1,1,1,1,1,1,1,1,1
4,0028a89964416dc9a8a66cc7fe25ef4e,0,1,1,1,0,1,0,0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5563,ffbf58ded2902366bcae7aa5e468556c,0,1,1,1,1,1,0,1,1,1,1,1,0,1
5564,ffc343f03f0c9dbd06439ddff42922c0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
5565,ffca215be2cb1505d931bd162da60104,0,1,1,1,1,1,0,1,0,1,0,1,1,0
5566,ffd7be58ee3c3fb47530ae7e4f251f88,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5567,fff2ca0333532d6348d5b4fa39028dd4,0,0,1,0,0,0,0,0,1,1,1,1,1,0

In [9]:
# Y: label from training dataframe
# you need to change your label from categorical encoding to one-hot encoding
Y = train_x.iloc[:,-5:]
Y

      t0  t1  t2  t3  t4
0      1   0   0   0   0
1      0   1   0   0   0
2      0   0   0   1   0
3      0   0   0   0   1
4      0   0   0   0   1
...   ..  ..  ..  ..  ..
5563   0   0   0   0   1
5564   1   0   0   0   0
5565   0   0   0   0   1
5566   1   0   0   0   0
5567   0   0   1   0   0

[5568 rows x 5 columns]

In [10]:
# split your dataset as training dataset and validation dataset
from sklearn.model_selection import train_test_split
X_train,X_valid,Y_train,Y_valid = train_test_split(X,Y,test_size = 0.2,random_state = 0)
print(X_train.shape)
print(Y_train.shape)

(4454, 14)
(4454, 5)

In [11]:
# build DNN model
import keras.models as k_models
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam
from tensorflow import keras

model = k_models.Sequential()
model.add(Dense(input_dim = 14,units=32))
model.add(Activation('relu'))
model.add(Dense(units=64))
model.add(Activation('relu'))
model.add(Dense(units=5))
model.add(Activation('sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 32)                480

 activation (Activation)     (None, 32)                0

 dense_1 (Dense)             (None, 64)                2112

 activation_1 (Activation)   (None, 64)                0

 dense_2 (Dense)             (None, 5)                 325

 activation_2 (Activation)   (None, 5)                 0

=================================================================
Total params: 2,917
Trainable params: 2,917
Non-trainable params: 0
_________________________________________________________________

In [12]:
import matplotlib.pyplot as plt
def show_model_loss(model,data_x,data_y):
    #Evaluate training result
    score = model.evaluate(x=data_x,y=data_y)
    print('\nTrain Loss:',score[0])
    print ('\nTrain Acc:', score[1])

def show_train_history(train_history,train,validation,label):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(label)
    plt.xlabel('Epoch')
    plt.legend(['train','validation'],loc='upper left')
    plt.show()

In [13]:
# start train model
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])

model.fit(x=X_train,y=Y_train,epochs=50)

Epoch 1/50
140/140 [==============================] - 1s 965us/step - loss: 0.4471 - accuracy: 0.5837
Epoch 2/50
140/140 [==============================] - 0s 929us/step - loss: 0.1794 - accuracy: 0.8978
Epoch 3/50
140/140 [==============================] - 0s 930us/step - loss: 0.1030 - accuracy: 0.9403
Epoch 4/50
140/140 [==============================] - 0s 886us/step - loss: 0.0788 - accuracy: 0.9520
Epoch 5/50
140/140 [==============================] - 0s 893us/step - loss: 0.0645 - accuracy: 0.9609
Epoch 6/50
140/140 [==============================] - 0s 907us/step - loss: 0.0555 - accuracy: 0.9648
Epoch 7/50
140/140 [==============================] - 0s 871us/step - loss: 0.0488 - accuracy: 0.9706
Epoch 8/50
140/140 [==============================] - 0s 901us/step - loss: 0.0446 - accuracy: 0.9717
Epoch 9/50
140/140 [==============================] - 0s 900us/step - loss: 0.0403 - accuracy: 0.9753
Epoch 10/50
140/140 [==============================] - 0s 900us/step - loss: 0.0376 - accuracy: 0.9775
Epoch 11/50
140/140 [==============================] - 0s 979us/step - loss: 0.0358 - accuracy: 0.9782
Epoch 12/50
140/140 [==============================] - 0s 914us/step - loss: 0.0335 - accuracy: 0.9807
Epoch 13/50
140/140 [==============================] - 0s 930us/step - loss: 0.0322 - accuracy: 0.9800
Epoch 14/50
140/140 [==============================] - 0s 936us/step - loss: 0.0307 - accuracy: 0.9823
Epoch 15/50
140/140 [==============================] - 0s 871us/step - loss: 0.0287 - accuracy: 0.9836
Epoch 16/50
140/140 [==============================] - 0s 936us/step - loss: 0.0280 - accuracy: 0.9834
Epoch 17/50
140/140 [==============================] - 0s 893us/step - loss: 0.0267 - accuracy: 0.9865
Epoch 18/50
140/140 [==============================] - 0s 893us/step - loss: 0.0261 - accuracy: 0.9861
Epoch 19/50
140/140 [==============================] - 0s 878us/step - loss: 0.0253 - accuracy: 0.9850
Epoch 20/50
140/140 [==============================] - 0s 986us/step - loss: 0.0249 - accuracy: 0.9863
Epoch 21/50
140/140 [==============================] - 0s 871us/step - loss: 0.0234 - accuracy: 0.9881
Epoch 22/50
140/140 [==============================] - 0s 929us/step - loss: 0.0234 - accuracy: 0.9890
Epoch 23/50
140/140 [==============================] - 0s 864us/step - loss: 0.0224 - accuracy: 0.9859
Epoch 24/50
140/140 [==============================] - 0s 930us/step - loss: 0.0217 - accuracy: 0.9874
Epoch 25/50
140/140 [==============================] - 0s 857us/step - loss: 0.0214 - accuracy: 0.9890
Epoch 26/50
140/140 [==============================] - 0s 864us/step - loss: 0.0201 - accuracy: 0.9879
Epoch 27/50
140/140 [==============================] - 0s 871us/step - loss: 0.0203 - accuracy: 0.9890
Epoch 28/50
140/140 [==============================] - 0s 929us/step - loss: 0.0196 - accuracy: 0.9885
Epoch 29/50
140/140 [==============================] - 0s 907us/step - loss: 0.0191 - accuracy: 0.9912
Epoch 30/50
140/140 [==============================] - 0s 871us/step - loss: 0.0196 - accuracy: 0.9890
Epoch 31/50
140/140 [==============================] - 0s 871us/step - loss: 0.0185 - accuracy: 0.9903
Epoch 32/50
140/140 [==============================] - 0s 871us/step - loss: 0.0183 - accuracy: 0.9915
Epoch 33/50
140/140 [==============================] - 0s 907us/step - loss: 0.0183 - accuracy: 0.9906
Epoch 34/50
140/140 [==============================] - 0s 922us/step - loss: 0.0176 - accuracy: 0.9901
Epoch 35/50
140/140 [==============================] - 0s 923us/step - loss: 0.0170 - accuracy: 0.9912
Epoch 36/50
140/140 [==============================] - 0s 1ms/step - loss: 0.0166 - accuracy: 0.9908
Epoch 37/50
140/140 [==============================] - 0s 1ms/step - loss: 0.0160 - accuracy: 0.9912
Epoch 38/50
140/140 [==============================] - 0s 1ms/step - loss: 0.0155 - accuracy: 0.9921
Epoch 39/50
140/140 [==============================] - 0s 922us/step - loss: 0.0162 - accuracy: 0.9917
Epoch 40/50
140/140 [==============================] - 0s 900us/step - loss: 0.0154 - accuracy: 0.9926
Epoch 41/50
140/140 [==============================] - 0s 871us/step - loss: 0.0153 - accuracy: 0.9924
Epoch 42/50
140/140 [==============================] - 0s 878us/step - loss: 0.0158 - accuracy: 0.9919
Epoch 43/50
140/140 [==============================] - 0s 914us/step - loss: 0.0149 - accuracy: 0.9928
Epoch 44/50
140/140 [==============================] - 0s 878us/step - loss: 0.0144 - accuracy: 0.9921
Epoch 45/50
140/140 [==============================] - 0s 894us/step - loss: 0.0168 - accuracy: 0.9899
Epoch 46/50
140/140 [==============================] - 0s 878us/step - loss: 0.0145 - accuracy: 0.9926
Epoch 47/50
140/140 [==============================] - 0s 915us/step - loss: 0.0139 - accuracy: 0.9926
Epoch 48/50
140/140 [==============================] - 0s 886us/step - loss: 0.0139 - accuracy: 0.9935
Epoch 49/50
140/140 [==============================] - 0s 878us/step - loss: 0.0133 - accuracy: 0.9944
Epoch 50/50
140/140 [==============================] - 0s 886us/step - loss: 0.0131 - accuracy: 0.9933

In [14]:
# validate your model using validation dataset
# After prediction, you need to change your result and label from one-hot encoding to categorical encoding
pred_train= model.predict(X_train)
scores = model.evaluate(X_train, Y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_valid= model.predict(X_valid)
scores2 = model.evaluate(X_valid, Y_valid, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))

140/140 [==============================] - 0s 626us/step
Accuracy on training data: 0.9939380288124084%
 Error on training data: 0.006061971187591553
35/35 [==============================] - 0s 736us/step
Accuracy on test data: 0.985637366771698%
 Error on test data: 0.014362633228302002

In [15]:
# using sklearn classification_report function to show your validation result
import sklearn

# change result and label from one-hot encoding to categorical encoding
y_true = []
for i in Y_valid.index:
    if Y_valid.loc[i,'t0'] == 1:
        y_true.append(0)
    elif Y_valid.loc[i,'t1'] == 1:
        y_true.append(1)
    elif Y_valid.loc[i,'t2'] == 1:
        y_true.append(2)
    elif Y_valid.loc[i,'t3'] == 1:
        y_true.append(3)
    elif Y_valid.loc[i,'t4'] == 1:
        y_true.append(4)
# print(y_true)
y_pred = pred_valid.argmax(axis=1)
# print(y_pred)

target_names = ['0','1','2','3','4']
print(sklearn.metrics.classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       444
           1       0.99      0.98      0.99       185
           2       0.98      0.99      0.98       137
           3       0.98      0.92      0.95       101
           4       0.96      0.99      0.98       247

    accuracy                           0.99      1114
   macro avg       0.98      0.98      0.98      1114
weighted avg       0.99      0.99      0.99      1114

# Testing phase

### Load Data

In [16]:
# load test.csv file as dataframe
raw_test_x = pd.read_csv('test.csv',)
raw_test_x.drop('created_time',axis=1,inplace=True)
test_x = raw_test_x.drop(['sniffer_loc'], axis=1)

### Data Preprocessing

In [17]:
# Preprocessing is the same as training

for i in range(1,15):
    test_x[str(i)] = 0

for i in range(raw_test_x.shape[0]):
    s = str(raw_test_x.loc[i,'sniffer_loc'])
    test_x.loc[i,s]=1

test_x = test_x.groupby(['mac_hash'], as_index=False).sum()
test_x.drop('mac_hash',axis=1,inplace=True)
print(test_x)

      1  2  3  4  5  6  7  8  9  10  11  12  13  14
0     1  1  1  1  1  1  0  1  1   0   0   0   0   0
1     0  1  1  1  1  0  1  1  1   1   0   0   0   0
2     0  1  1  1  1  1  0  1  1   1   1   1   1   1
3     0  0  1  1  1  1  1  1  1   1   1   1   1   1
4     0  1  1  0  1  1  0  1  1   0   1   1   1   0
...  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..
1386  0  0  0  0  0  0  0  0  0   0   0   1   0   0
1387  0  1  1  1  1  1  0  1  1   1   1   1   1   1
1388  0  0  0  0  0  0  0  1  0   0   0   0   0   0
1389  0  1  1  1  1  0  1  0  0   0   0   0   0   0
1390  0  1  1  1  1  1  1  1  1   1   1   1   1   1

[1391 rows x 14 columns]

### Predict the result using your model

In [18]:
# Prediction
pre_test_x = model.predict(test_x)
ans_y = pre_test_x.argmax(axis=1)
ans_y

44/44 [==============================] - 0s 791us/step

array([1, 1, 4, ..., 0, 1, 4], dtype=int64)

In [19]:
# Generate submit.csv
mac = raw_test_x.drop(['sniffer_loc'], axis=1)
mac = mac.groupby(['mac_hash'], as_index=False).sum()

submission = pd.DataFrame({
    "mac_hash": mac["mac_hash"],
    "label": ans_y
    })

submission.to_csv("submit" +'.csv', index=False)
display(submission)

                              mac_hash  label
0     004c76bfe9f7b20f3651e0bcbd8eee9e      1
1     0084303d531091816387956ea26b86eb      1
2     00872a1ee635c2619454350b96b94103      4
3     00a5f69fc7719ba29c7b202f292dbafb      4
4     00ad41313f1f637e079c1a9d9a857d12      4
...                                ...    ...
1386  ff6883d04de66c6d4859928ec9d3f642      0
1387  ff7b41d3b33fb7d0b6704f1093173c40      4
1388  ffa5692a2dac937f456280c433961ea6      0
1389  ffcaf0f29c6bede7b5cd9bc807c31715      1
1390  ffd0c4403c3c44dcbe4772821b032252      4

[1391 rows x 2 columns]